### ISSUE TITLE
Documentation for API '/hosts/statuses'

### ISSUE THREAD

**Issue by piccobit** [spotify/helios#1001]
Hi, 

I'm desperately trying to get some output from the API call '/hosts/statuses'.

My node.js application always receives an error 422.

An example with either curl or wget would be fine for me.

TIA, 

~ HD ~

**Comment by mattnworb** [comment]
Hi @piccobit , `HTTP 422 Unprocessable Entity` is usually returned if the request body can't be parsed or understood. 

Do you know exactly what headers and request body your node.js code is sending? My advice would be [to carefully examine the request you are sending](http://stackoverflow.com/questions/12964517/how-to-log-outgoing-https-requests-from-node-within-webstorm) and compare it with the output of your `curl` commands with the `-v` flag.

For reference, the [`/hosts/status` endpoint](https://github.com/spotify/helios/blob/015d48b2835c708ded4a60e8775816c37144d599/helios-services/src/main/java/com/spotify/helios/master/resources/HostsResource.java#L216) is expecting a list of hostnames (which can be an empty array) in the POST body.
