### ISSUE TITLE
do not set deployment group state to FAILED on rollingUpdate errors caused by HOSTS_CHANGED 

### ISSUE THREAD

**Issue by mattnworb** [spotify/helios#1019]
# Background 
Within the helios-master and the state stored in zookeeper, a deployment group can have one of three states. It can either be ROLLING_OUT, FAILED, or DONE. 

The `/deployment-group/{name}/status` endpoint in the API translates this internal state into one of four values to return in the response:
- if nothing is stored, return IDLE.
- if ROLLING_OUT, return ROLLING_OUT
- if FAILED, return FAILED
- otherwise, return ACTIVE.

The internal state is set to ROLLING_OUT at the start of a rolling-update, unless there are no tasks in the deployment plan. 

The internal state is set to DONE when the last task in the plan successfully completes (or if there were no tasks in the plan to start with). 

The internal state is set to FAILED if the deployment group is set to "stopped" by a user (via `helios stop-deployment-group` or the `/deployment-group/{name}/stop` endpoint) or when a rolling-update operation times out - for instance, if the image being deployed failed to pull or the container continually exited.

Prior to #932, a deployment group in the FAILED state would not have any action taken when the hosts in a deployment group were detected to change. For instance, if new hosts were added to the group (due to scaling up or auto-scaling, etc), no job would be deployed to them by the helios-master. This would cause confusion for users who were trying to provision more capacity for their deployment group, as the automatic deployment of the job may have failed for transient reasons on an initial new host, and then nothing would be automatically deployed to additional new hosts (possibly days later). Since there is no notification when a deployment group changes state, often these users would be unaware of the state change and puzzled as to why the capacity of their job was not increasing.

PR #932 adjusted this logic so that when the hosts in a group change, an additional check would be performed for groups in the FAILED state. If the group is in FAILED state and the reason for the last rollingUpdate operation was the HOSTS_CHANGED event, then the automatic deployment of the job to a new host is allowed to proceed. If the reason for the last rollingUpdate operation (which caused the transition to the FAILED state) was a manual invocation of `helios rolling-update`, then the automatic deployment is prevented and no action is taken.

This still causes some confusion for users though, as it is not obvious what will happen when a deployment group is in the FAILED state and new hosts are added to the group. If a user runs `helios deployment-group-status my-group` and sees `Status: FAILED`, they have no way of knowing from the `deployment-group-status` command's output if the job will be deployed to newly provisioned hosts or not. 

For reference, the full output of the command looks like:

```sh
$ helios deployment-group-status my-group
Name: my-group
Job Id: my-group:1.2.3
Status: FAILED
Host selectors:
  role = mygroup

HOST                 UP-TO-DATE    JOB                                    STATE
( ... a list of hosts in the group ... )
```

# Proposal

I think it would be simpler, both for the user and for the implementation, if we changed the behavior so that a deployment group's state is only changed to FAILED during errors in the updates from a manual invocation of `helios rolling-update`. If a rolling operation that was caused by the HOSTS_CHANGED event ends up timing out, the state of the group should not change.

This would remove the confusion that users experience when they see that their group has a state of FAILED about whether or not the job will be deployed to new hosts by simplifying the meaning of the FAILED state. Groups that are FAILED will not have any operations taken on them at all, until a new `helios rolling-update` is done. The FAILED state will no longer have a second conditional meaning that changes based on the (non-exposed) cause of the last rolling update.

**Comment by mattnworb** [comment]
@negz @gimaker @davidxia @rohansingh @matslina

**Comment by negz** [comment]
I still wish we failed rolling updates rather than the group those updates happen on, but I know how hard that is to implement. I think this proposal is a good compromise that will simplify our code.
