### ISSUE TITLE
New home (GroupId) for raven-java artifacts, active maintenance has moved

### ISSUE THREAD

**Issue by bretthoerner** [spotify/helios#1087]
About a year ago we moved the [raven-java](https://docs.sentry.io/clients/java/) artifacts to a new home under the [com.getsentry.raven](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.getsentry.raven%22) `GroupId`. 🎆 

All maintenance and future development is going on under the new `GroupId`. Note that the package names also changed, so `import`s and class names in configuration (such as logging integrations) will need to be renamed. There shouldn't be any other changes required unless you made customizations to Raven itself, and those *should* still be minor.

We've made a lot of improvements and bugfixes and have a lot more planned, so check it out when you have time. 😄 

The [documentation](https://docs.sentry.io/clients/java/) has been improved if you have any questions, or just ask me here!

**Comment by davidxia** [comment]
Thanks. I think we don't use sentry and hence raven anymore though. But I suspect a bot wrote this for you? :)

**Comment by davidxia** [comment]
Ah, nvm. We still support sentry.
