### ISSUE TITLE
Should helios-agent rerun healthchecks when it restarts?

### ISSUE THREAD

**Issue by davidxia** [spotify/helios#1090]
Currently helios-agent runs health checks for jobs when it deploys them. If a job is stuck in HEALTHCHECK state and you restart the agent, the agent won't run health checks for existing containers. So these containers can go from HEALTHCHECK to RUNNING even if they fail the health check.

Should helios-agent rerun healthchecks when it restarts?

**Comment by mattnworb** [comment]
small note: restarting the helios-agent itself won't cause the containers to be re-created, I think you mean to say if docker is restarted, or the containers otherwise exit.

**Comment by davidxia** [comment]
I think helios will rerun healthchecks if the container is killed. I'm talking specifically about restarting helios-agent. I know it will skip over the healthcheck if it sees the container is already running.

**Comment by mattnworb** [comment]
Ah sorry I misunderstood completely. You are right of course - the healthcheck is run any time that TaskRunner thinks it needs to create and start the container; however, if the container is already running when helios-agent starts up, then it skips the healthcheck prior to registering the already-running-container in the service registration.
