### ISSUE TITLE
Ubuntu 14.04 LTS binaries and the java8-runtime-headless dependency

### ISSUE THREAD

**Issue by ilkka** [spotify/helios#1101]
It seems that the [deployment instructions](https://github.com/spotify/helios/blob/master/docs/how_to_deploy.md) are not enough to get a Helios cluster running in at least DigitalOcean using their Ubuntu 14.04 images. The more serious issue is that the helios packages depend on "java8-runtime-headless" which does not seem to be available (`aptitude search '~Pjava8-runtime-headless'` returns zero results). The less serious one is that the package `lxc-docker` referred to by the doc is not available in Ubuntu 14.04, it's `docker.io`.

**Comment by mattnworb** [comment]
Thanks for the report @ilkka . Do you happen to know what the better package would be to depend on to get a java8 runtime? Would be happy to merge a PR to fix this if you have the time

**Comment by ilkka** [comment]
Well, if the README is correct in stating that Java 7 is enough, `java7-runtime-headless` *is* available in Ubuntu 14.04, provided by `openjdk-7-jre-headless`. I guess building in a Java 7 environment and changing the package `control` files might be enough to test? I'll try it out when I have some slack.

**Comment by mattnworb** [comment]
we upgraded the server-side components to Java 8 in https://github.com/spotify/helios/pull/384 ; sorry that the README is incorrect
