### ISSUE TITLE
helios-testing should shade/relocate its dependency on Guava

### ISSUE THREAD

**Issue by mattnworb** [spotify/helios#1119]
Since helios-testing relies on helios-client, it drags in the dependency on Guava for anyone using helios-testing to write integration tests. 

We've seen a number of internal users at Spotify where changes in the version of Guava used cause a lot of headaches because Guava has been deprecated/removing things in recent versions. In fact we have so many users internally that it is becoming really hard for Helios to change what version of Guava it uses - in either direction (upgrade or downgrade) - without affecting users of helios-testing.

Since helios-testing as a library doesn't really care what version of Guava the using-code is using - it just needs a certain version for its own internal needs - it would seem like a perfect candidate for [relocating the Guava dependency](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html) in the jar that we ship for helios-testing.

There may be some obstacles that prevent us from implementing this for helios-testing (for instance if other libraries used by Helios are in turn using Guava as well), but it seems like something worth investigating more.

**Comment by rydenius** [comment]
For us, the last release of helios-testing that was de facto Guava 19 runtime compatible was 0.9.107.
