### ISSUE TITLE
Docker Compose 

### ISSUE THREAD

**Issue by Razikus** [spotify/helios#1185]
Hello, are we able to send DockerCompose-based job to the host?

How to for example construct service of MySQL and Alpine with WordPress preinstalled (basic usage)?

**Comment by davidxia** [comment]
Are you asking if there's a way for one helios job to run multiple containers?

If so no, helios is designed for running a single container per job. It's unlikely we'll add multi-container per job functionality. If you want to run multiple containers in a coordinated way, I'd suggest using Docker compose by itself or something like Kubernetes.
