### ISSUE TITLE
helios remove: unexpected ambiguous job reference error

### ISSUE THREAD

**Issue by danielnorberg** [spotify/helios#120]
```
$ helios remove test:1
Ambiguous job reference: test:1

$ helios jobs test:1
JOB ID                              NAME                      VERSION    HOSTS    COMMAND                              ENVIRONMENT
cassandra-test:1:5d62594            cassandra-test            1          0
test:1:153de22                      test                      1          0        sh -c "while :; do sleep 1; done"
user-profile-view-test:1:023f78c    user-profile-view-test    1          0        -vvv
```

Given that helios enforces the uniqueness of `test:1`, it should not be ambiguous. Maybe we shouldn't do substring job id search the way we do.

**Comment by davidxia** [comment]
I haven't heard complaints about this. Here's the substring search code for reference https://github.com/spotify/helios/blob/master/helios-services/src/main/java/com/spotify/helios/master/resources/JobsResource.java#L104

``` java
if (entry.getKey().toString().contains(q)) {
```

**Comment by mattnworb** [comment]
I've seen some anecdotes where people create jobs like `foobar:1` and `foobar:1-darkload` and then are confused when `helios deploy foobar:1` gets the ambiguous reference error.
