### ISSUE TITLE
Use Docker instead of Vagrant

### ISSUE THREAD

**Issue by mrfuxi** [spotify/helios#15]
It would be very nice, if tool for orchestration Docker would actually use Docker instead of Vagrant :)

**Comment by aidanhs** [comment]
Docker has restart policies (now), which would keep it running.

My question would be how you'd manage upgrades of helios (as entertaining as it'd be, I'm not sure it makes sense to have the helios agent managing the helios agent - you probably don't want to ever be able to undeploy, for example!). 
In theory it should be as simple as persisting the agent state directory. I'll have to try it and see.

**Comment by rohansingh** [comment]
With [helios-solo](https://github.com/spotify/helios/blob/master/docs/helios_solo.md), we now have Helios-in-Docker for development purposes. helios-solo brings up a simple one-agent cluster in a Docker container.

@aidanhs, with helios-solo, upgrades are done by running `helios-use latest`. However, this is a destructive operation that wipes your whole helios-solo instance. Persisting the state directory is definitely a possibility, probably would be a pretty small change to [the `docker run` command in `helios-up`](https://github.com/spotify/helios/blob/master/solo/helios-up#L93).

In addition to helios-solo, we actually also build a helios-master and helios-agent Docker image with the `build-images` Maven profile:

    mvn -P build-images package

These are more flexible and could, in theory, be configured to run in a cluster configuration. We use them for integration testing, but I don't see us recommending them as the blessed way to install Helios and run a cluster.

**Comment by rohansingh** [comment]
Closing this issue since we no longer use or recommend Vagrant.
