### ISSUE TITLE
Helios web front-end??

### ISSUE THREAD

**Issue by alejandrojnm** [spotify/helios#283]
Hi do not know if this is place to ask. Helios has a restful API for interacting with helios-master as does helios cli. I would like to contribute to the project, creating a front-end to manage helios via web.

I hope to help this project grow.
Thanks for everything.

**Comment by aidanhs** [comment]
Quite interested in a UI.
@davidxia is yours still available somewhere? I'm a fan of react myself but listing images from a registry sounds pretty good for what I'm thinking of.

**Comment by alejandrojnm** [comment]
Hello @davidxia and @aidanhs, I have been complicated, but I'm working again with the helios-manager, I'm making some changes to the UI, I hope to upload them as soon as they finished, and will also be made to create jobs, in addition to the deploy and undeploy the jobs

**Comment by marsmensch** [comment]
@alejandrojnm very cool, sounds like something i want to test-drive asap ;-)

**Comment by alejandrojnm** [comment]
I hope this week, push all commit to github :D

**Comment by alejandrojnm** [comment]
@marsmensch, @davidxia, @aidanhs  this is how it looks. so far this is how this being.

![1](https://cloud.githubusercontent.com/assets/7557763/9275034/478c1bde-4268-11e5-893a-4abddf25eea2.png)
![2](https://cloud.githubusercontent.com/assets/7557763/9275029/471d8606-4268-11e5-839e-f62e82abc054.png)
![3](https://cloud.githubusercontent.com/assets/7557763/9275027/47147e08-4268-11e5-9d0e-bfdac610447a.png)
![4](https://cloud.githubusercontent.com/assets/7557763/9275026/46fe13fc-4268-11e5-8272-b775e6b68ae1.png)
![5](https://cloud.githubusercontent.com/assets/7557763/9275033/4757a958-4268-11e5-8297-4cf40c2dd742.png)
![6](https://cloud.githubusercontent.com/assets/7557763/9275028/471b5638-4268-11e5-9141-386756a49caa.png)
![7](https://cloud.githubusercontent.com/assets/7557763/9275030/471fb200-4268-11e5-8813-be8d4739f501.png)
![8](https://cloud.githubusercontent.com/assets/7557763/9275031/473ab910-4268-11e5-8402-2c52d2760b6b.png)
![9](https://cloud.githubusercontent.com/assets/7557763/9275032/474574ae-4268-11e5-8558-9c81b507beb6.png)

**Comment by marsmensch** [comment]
I like the look, clean and smooth. Maybe a little too red for the details
menu for my taste, but thats really not that important atm. Well done!

**Comment by alejandrojnm** [comment]
Hello @marsmensch i up the latest changes, still missing some things like create and deploy job to job, and I'm working to list the images of the private registry, I'm working on it. Hope you try and tell if a need change something or add something

**Comment by marsmensch** [comment]
Hi @alejandrojnm, will test-drive on wednesday and get back to you here. Thanks!

**Comment by ArtworkAD** [comment]
:+1:

**Comment by berlincityboy** [comment]
Awesome. Does this UI need to run on the same instance as the Helios master?

**Comment by davidxia** [comment]
It doesn't. It just needs to be able to talk to the Helios master http api

On Wednesday, October 14, 2015, Konrad <notifications@github.com> wrote:

> Awesome. Does this UI need to run on the same instance as the Helios
> master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/helios/issues/283#issuecomment-148255222>.
>


-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by davidxia** [comment]
Sorry to kill a once active but now stale thread. If there's still any interest in such a GUI it can probably be discussed and developed in another project. We're unlikely to add any such code into this project.
