### ISSUE TITLE
Undeployment of containers takes around 2 minutes

### ISSUE THREAD

**Issue by vanomashey** [spotify/helios#314]
Hi guys,

We are trying helios for docker management. Everything is fine except of docker undeployment. I takes around 2 minutes to undeploy the docker containers. Deployment is very fast but undeployment takes time. Can you give me a hint what might be wrong? 

i have checked the verbose logs and there is no errors within this 2 minutes. 

Any help would be appreciated. 

Ivan

**Comment by davidxia** [comment]
@vanomashey Is this still an issue?

**Comment by vanomashey** [comment]
Nope. Not anymore.

2015-01-06 18:42 GMT+01:00 David Xia <notifications@github.com>:

> @vanomashey <https://github.com/vanomashey> Is this still an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/helios/issues/314#issuecomment-68901369>.
>



-- 
-- 
Best Regards,
Ivan Mashey,
Mobile: +31655887134
Skype: vano_mashey


www.attractgroup.com

**Comment by davidxia** [comment]
Good. I'll close this then. Let us know if you have more questions.
