### ISSUE TITLE
Authentication when pulling from 3rd party repos not supported

### ISSUE THREAD

**Issue by jypma** [spotify/helios#318]
I could not find how to have docker authenticate to a 3rd party repo for pulling, when creating a helios job. This would be the equivalent to doing `docker login` before a `docker pull myserver.com/path/image`, when interacting with docker from the command line. In our case, `myserver.com` is `quay.io`.

It seems that docker's REST API wants an `X-Registry-Auth` header on the `/pull` call; I unfortunately could find no trace of support for that in the spotify java docker client either.

Am I holding it wrong? How are others using private docker repos? Unauthenticated behind a firewall?

**Comment by davidxia** [comment]
@jypma I see that our docker-client can set the `X-Registry-Auth` header on docker [pull](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L652) and [push](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L681).

I don't think helios calls [authConfig()](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L1108) which sets the `authConfig` attribute in PollingDockerClient that extends DefaultDockerClient.

We are not using X-Registry-Auth. I'm wondering how this would work. We'd probably want the Helios agent to be able to pull from different registries. So we'd want to set different auth headers depending on where the docker-client is pulling from, ie depending on the docker image ID.

This is where I'm not sure how it'd work. Based on the current design of Helios code, one place to put the auth creds is in the Helios job. When the Helio sagent deploys or starts a job, it reads in the auth creds and passes that to docker-client which can then pull the image from the private registry.

I'm not sure it's ok to have auth creds in plaintext in a Helios job though...

**Comment by jypma** [comment]
@davidxia Thanks for your comments. It's nice to see that indeed authorization support has been added to the docker client since I wrote the issue, so that's indeed available now.

As far as where to store the credentials, I see several possibilities:

1. Put them together with the job config. The password is visible to the machine creating the job, on helios-master, in zookeeper, and on the machine running helios agent to pull.
2. Manage them directly in zookeeper through helios-master API, write-only. The password is visible on helios-master, in zookeeper, and on the machine running helios agent to pull.
3. Have helios-agent read a docker-like `~/.helioscfg` file that contains passwords, readable only be the user helios-agent is running under. No API changes. The password is only stored on each helios-agent machine that actually needs to pull.

Option (3) seems most secure to me, and possibly fastest to implement. However, it's also less generic, as it would only allow one fixed username/password to authenticate against any one registry. That would cover most typical machine-initiated build / test / deploy jobs though...

What do you think?

**Comment by davidxia** [comment]
Yea I realized this too. Are you simply using docker without Helios and
with a private registry requiring auth?

On Wednesday, January 7, 2015, Jan Ypma <notifications@github.com> wrote:

> Unfortunately, it seems that DefaultDockerClient only has room for 1
> authConfig object that is then sent along with a pull command to any
> repository. What you'd want to do instead is have an authConfig per
> repository, or even pass in the authConfig as an argument to the pull
> method. So, still changes needed to the base docker client, or some nasty
> overriding and copying of methods into the helios project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/helios/issues/318#issuecomment-69024585>.
>


-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by jypma** [comment]
Yes, we're using quay.io, but right now we're manually copying stuff from there into a private repo, so helios can make docker pull from it. We prefer not managing our own docker registry though, since our images can grow quite big and we'd rather not manage the storage and access ourselves.

**Comment by davidxia** [comment]
@jypma totally agree with your points on option 3 above. I've been punting on this for a while because you're the first to ask for this. @Kobolog What do you think?

**Comment by Kobolog** [comment]
Since we are going to implement some mechanics to work with secrets at some point, I'd say we should avoid doing it in a fast-and-easy way right now and instead implement some extensible way of providing secrets to Helios. Maybe a pluggable SecretProvider, so that it could be a FileProvider for @jypma case?

**Comment by davidxia** [comment]
I stubbed out a helios-secret-provider module that lets you plugin secret providers. It's the same pattern as helios-service-registration if we want to take that approach. https://github.com/spotify/helios/tree/dxia/secret-provider

**Comment by davidxia** [comment]
@Kobolog @jypma I just added per pull auth headers to docker-client https://github.com/spotify/docker-client/pull/118

**Comment by erikgrinaker** [comment]
Docker stores authentication details for `docker login` in the file `~/.docker/config.json`, which looks something like this:

```json
{
        "auths": {
                "registry.domain.com": {
                        "auth": "dXNlcm5hbWU6cGFzc3dvcmQ=",
                        "email": "user@domain.com"
                }   
        }   
}
```

The `auth` string is in standard HTTP `Authorization` format, i.e. the base64-encoded value of `<username>:<password>`. This is obviously completely insecure, but anyone using private registries will likely have these files lying around anyway.

Is there any chance of having Helios support this format? The alternative right now seems to be allowing full read-access to our private registry from our server networks, which is even less secure.

**Comment by mattnworb** [comment]
@erikgrinaker one possible solution would be to add flags to the helios-agent for either a config file that resembles `~/.docker/config.json` or the server/auth token/email parameters themselves, and pass those down to the DockerClient used within the agent. I don't think it is very high on our radar at the moment to add this to helios as we don't have a use case for it internally at Spotify, but we would be very happy to review any PRs that added this support.

**Comment by elifarley** [comment]
This is related to #462.

**Comment by elifarley** [comment]
@mattnworb @erikgrinaker @davidxia here's a PR that adds a command-line switch (#948)  to enable the use of `~/.docker/config.json`.
