### ISSUE TITLE
Undeploying job does not work if zookeeper namespace is used

### ISSUE THREAD

**Issue by jypma** [spotify/helios#322]
I'm running helios with `--zk-namespace helios`. When trying to undeploy a job, helios always returns `JOB_NOT_FOUND`. The reason for this, is that `ZookeeperMasterModel.undeployJob` turns any `NoNodeException` into a `JobNotDeployedException`. That by itself is OK, but it seems that helios forgets about the zookeeper namespace in some of its ZK requests during undeploy. I was not able to find which request, though. Here's the (sanitized) ZK debug log for the undeploy call:

```
450038 [dw-33 - DELETE /hosts/r1.eu1.test.int.ts.tt/jobs/es:v3:93a150116e9830d8171b17262de376553277c4b0?user=jan] INFO  c.s.h.master.ZooKeeperMasterModel - undeploying es:v3:93a150116e9830d8171b17262de376553277c4b0: r1.eu1.test.int.ts.tt 
450040 [MasterMain STARTING-SendThread(gw1.eu1.test.int.ts.tt:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x149f6de6ba10009, packet:: clientPath:null serverPath:null finished:false header:: 140,4  replyHeader:: 140,4688,0  request:: '/helios/config/hosts/r1.eu1.test.int.ts.tt,F  response:: ,s{137,137,1417448169505,1417448169505,0,3,0,0,0,3,142}  
450041 [MasterMain STARTING-SendThread(gw1.eu1.test.int.ts.tt:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x149f6de6ba10009, packet:: clientPath:null serverPath:null finished:false header:: 141,4  replyHeader:: 141,4688,0  request:: '/helios/config/hosts/r1.eu1.test.int.ts.tt/jobs/es:v3:93a150116e9830d8171b17262de376553277c4b0,F  response:: #7b2[...]d7d,s{207,259,1417448801803,1417449216339,3,1,0,0,415,1,207}  
450042 [MasterMain STARTING-SendThread(gw1.eu1.test.int.ts.tt:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x149f6de6ba10009, packet:: clientPath:null serverPath:null finished:false header:: 142,4  replyHeader:: 142,4688,0  request:: '/helios/config/jobs/es:v3:93a150116e9830d8171b17262de376553277c4b0,F  response:: #7b2[...]d7d,s{202,202,1417448747221,1417448747221,0,2,0,0,373,2,202}  
450044 [MasterMain STARTING-SendThread(gw1.eu1.test.int.ts.tt:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x149f6de6ba10009, packet:: clientPath:null serverPath:null finished:false header:: 143,8  replyHeader:: 143,4688,-101  request:: '/config/hosts/r1.eu1.test.int.ts.tt/jobs/es:v3:93a150116e9830d8171b17262de376553277c4b0,F  response:: v{}  
```

As you can see, the last request was for `/config/hosts/r1.eu1.test.int.ts.tt/jobs/...`, forgetting about the `/helios` prefix, resulting in ZK not finding in the node, resulting (presumably) in helios concluding that the job doesn't exist.

**Comment by noaresare** [comment]
I can reproduce this with current master (c12daf62) by setting up a vagrant box and appending `--zk-namespace helios` to HELIOS_MASTER_OPTS in /etc/default/helios-master and HELIOS_AGENT_OPTS in /etc/default/helios-agent and and restarting them in that order.

Once that is done when you create a job with `helios create bar:v1 nginx` and start it with `helios deploy bar:v1 ubuntu-14` you can't undeploy it with `helios undeploy bar:v1 ubuntu-14`, the status returned being JOB_NOT_FOUND.
