### ISSUE TITLE
Users can find out easily which versions of Helios are compat with which versions of Docker

### ISSUE THREAD

**Issue by davidxia** [spotify/helios#342]
Sometimes users don't know which versions of Helios are compatible with which versions of Docker. Is this information hard to find out? Maybe `helios --version` can say that?

**Comment by rculbertson** [comment]
I think it would be reasonable to show what version of docker each build was tested against. Showing a range of versions might be tough unless we start testing against multiple versions.

**Comment by davidxia** [comment]
Yea I agree.

On Sunday, January 25, 2015, Ryan Culbertson <notifications@github.com>
wrote:

> I think it would be reasonable to show what version of docker each build
> was tested against. Showing a range of versions might be tough unless we
> start testing against multiple versions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/helios/issues/342#issuecomment-71381376>.
>


-- 
David Xia
Software Engineer
dxia@spotify.com
