### ISSUE TITLE
Remove need to explicitly deregister helios agents?

### ISSUE THREAD

**Issue by davidxia** [spotify/helios#362]
Remove need to explicitly deregister helios agents when a host with the same hostname as a down agent tries to register. This happens when someone reinstalls their agent machine.

Lots of users get tripped up by this. This behavior doesn't seem to be very useful.

**Comment by Kobolog** [comment]
What happens if a new agent is registered replacing the old one, but the old one is actually still running its jobs?

**Comment by davidxia** [comment]
We should prohibit replacement of a registered agent that's UP and require explicit deregistration first. Only allow replacement of registered agents that are DOWN.

**Comment by rasmusbergpalm** [comment]
Yes! We've stumbled on this a few times. :sparkling_heart:

**Comment by davidxia** [comment]
@rasmusbergpalm My tests in this PR https://github.com/spotify/helios/issues/382 above keep failing. I haven't had time to fix it though.
