### ISSUE TITLE
Tags for service endpoints

### ISSUE THREAD

**Issue by carlanton** [spotify/helios#367]
Hi again!

In a Consul service definition it's possible to tag a service with some arbitrary tags:
```
{
  "service": {
    "name": "redis",
    "tags": ["master", "web-scale"],
    "port": 8000
}
```
It would be very useful for us (and everyone else using the helios-consul plugin) if we could add this to the Helios job model and expose it to helios-consul through ```ServiceRegistration.Endpoint```.

A Helios job of the Redis example could look something like this:
```
{
  "command": ["redis", "..."],
  "ports": {
    "default": {
      "externalPort": 8080,
      "internalPort": 8080,
      "protocol": "tcp"
    }
  },
  "registration": {
    "fooservice/default": {
      "ports": {"http": {}},
      "tags": ["master", "web-scale"]
    }
  }
}
```

I guess that you can't use tags with Nameless, but it would be awesome for helios-consul :-) I can try to make a PR for it if you want!

**Comment by davidxia** [comment]
Oh interesting. I see [here](http://www.consul.io/docs/agent/services.html):

> The tags is a list of opaque value to Consul, but can be used to distinguish between "master" or "slave" nodes, different versions, or any other service level labels 

Do you know how many people are using helios-consul?

**Comment by carlanton** [comment]
No, I guess it's just us at SVT for now :-) Maybe we should write blog post or something about it because Helios and Consul fits together surprisingly well.

SVT or "Sveriges Television", is the Swedish national public TV broadcaster. I'm working with infrastructure in "SVT interactive", were we develop SVT's online services (svt.se, svtplay.se etc.). We started experimenting with Helios and Consul last year for our new microservice architecture. It's working really well and we will deploy it to production during the spring :-)

**Comment by rohansingh** [comment]
We actually talked about this a while ago at Spotify. If I recall, we punted on it just because it wasn't high-priority and we found other ways to do what we wanted to use tags for.

Seems like a pretty sane feature to have though.

**Comment by davidxia** [comment]
@carlanton really cool to see you guys using it!
