### ISSUE TITLE
How to build Helios Agent for Centos?

### ISSUE THREAD

**Issue by dligthart** [spotify/helios#417]
How to build Helios Agent for Centos?

Can you provide a guide for this?

Thank you.

**Comment by dligthart** [comment]
Tests in error:
  HealthCheckTest.testTcp:138->SystemTestBase.awaitTaskState:932 » Timeout

Tests run: 87, Failures: 0, Errors: 1, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Helios Parent ..................................... SUCCESS [3.464s]
[INFO] Helios Client ..................................... SUCCESS [14.232s]
[INFO] Helios Service Registration ....................... SUCCESS [1.052s]
[INFO] Helios Tools ...................................... SUCCESS [6.494s]
[INFO] Helios Testing Common Library ..................... SUCCESS [2.214s]
[INFO] Helios Services ................................... SUCCESS [1:53.860s]
[INFO] Helios System Tests ............................... FAILURE [20:55.925s]
[INFO] Helios Testing Library ............................ SKIPPED
[INFO] Helios Integration Tests .......................... SKIPPED
[INFO] Helios API Documentation .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23:19.647s
[INFO] Finished at: Fri Mar 06 12:22:49 UTC 2015
[INFO] Final Memory: 27M/118M
[INFO] -----------------------------------------------------------------------

**Comment by dligthart** [comment]
wget http://mirror.cogentco.com/pub/apache/zookeeper/stable/zookeeper-3.4.6.tar.gz
    5  ls
    6  tar xzvf zookeeper-3.4.6.tar.gz -C /usr/local/
    7  sudo tar xzvf zookeeper-3.4.6.tar.gz -C /usr/local/
    8  cd /usr/local/zookeeper-3.4.6/conf
    9  ls
   10  cp zoo_sample.cfg zoo.cfg
   11  ls
   12  vim zoo
   13  sudo yum install  vim -y
   14  ls
   15  sudo vim zoo.cf
   16  sudo vim zoo.cfg
   17  ls
   18  cd ..
   19  ls
   20  cd bin
   21  ls
   22  sudo ./zkServer.sh start
   23  sudo yum install maven -y
   24   ls
   25  cd ..
   26  l
   27  scd ~
   28  cd ~
   29  ls
   30  sudo yum install docker -y
   31    sudo yum install git -y
   32  ls
   33  sudo git clone https://github.com/spotify/helios.git
   34   ls
   35  cd helios/
   36  ls
   37  sudo mvn clean test
   38  sudo docekr ps
   39  sudo docker ps
   40  sudo service docker start
   41  sudo mvn clean test
   42      lsof
   43  sudo yum install lsof -y
   44  sudo mvn clean test

**Comment by dligthart** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Helios Parent ..................................... SUCCESS [35.883s]
[INFO] Helios Client ..................................... SUCCESS [51.505s]
[INFO] Helios Service Registration ....................... SUCCESS [22.005s]
[INFO] Helios Tools ...................................... SUCCESS [43.944s]
[INFO] Helios Testing Common Library ..................... SUCCESS [42.727s]
[INFO] Helios Services ................................... SUCCESS [3:42.758s]
[INFO] Helios System Tests ............................... SUCCESS [3:34.844s]
[INFO] Helios Testing Library ............................ SUCCESS [3:18.733s]
[INFO] Helios Integration Tests .......................... SUCCESS [4:57.484s]
[INFO] Helios API Documentation .......................... SUCCESS [2:20.108s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21:12.317s
[INFO] Finished at: Fri Mar 06 13:58:03 UTC 2015
[INFO] Final Memory: 53M/264M
[INFO] ------------------------------------------------------------------------

when running: 
sudo mvn clean compile site

**Comment by dligthart** [comment]
sudo ./helios
ls: cannot access /home/centos/helios/bin/../helios-tools/target/helios-tools*-shaded.jar: No such file or directory
dirname: missing operand
Try 'dirname --help' for more information.
basename: missing operand
Try 'basename --help' for more information.

**Comment by dligthart** [comment]
Running mvn install now

**Comment by dligthart** [comment]
mvn install worked but didn't install - it just created the executables.

**Comment by rohansingh** [comment]
`mvn install` just installs JAR's to your local repo, it doesn't install Helios anywhere.

If you wish to run Helios, here are some instructions for the "manual" approach:
https://github.com/spotify/helios#manual-approach

You can then run `helios-agent` or `helios-master` however you'd like, maybe as part of some init system (I'm not familiar with CentOS). Alternatively, you could take a look at the Debian packages and try to port them somehow (`./src/deb`).

The final possibility is to use `alien` to convert our release deb's to rpm's, but that's probably not a good idea.

Hopefully this answers your question.
