### ISSUE TITLE
Helios 0.8.213 - "helios inspect" displays incomplete job

### ISSUE THREAD

**Issue by evgeny-goldin** [spotify/helios#418]
$ helios -z 'http://127.0.0.1:5801' inspect "nginx:v1"
    Id: nginx:v1:50aa1e78592550f60780432cf667406294480e1e
    Image: nginx:1.7.9
    Command: []
    Env:
    null
    $ helios --version
    Spotify Helios CLI 0.8.213
    $

**Comment by evgeny-goldin** [comment]
With previous version:

    $ helios -z 'http://helios-master.vm:5801' inspect "nginx:v1"
    Id: nginx:v1:50aa1e78592550f60780432cf667406294480e1e
    Image: nginx:1.7.9
    Token:
    Command: []
    Env:
    Ports: http=80:8080/tcp
    Reg: nginx/http=http
    Grace period (seconds): null
    Volumes:
    $ helios --version
    Spotify Helios CLI 0.8.200
    $

**Comment by davidxia** [comment]
```
helios inspect -d DOMAIN helioscanary-service:0.0.1-SNAPSHOT-27b096a:342e49e
Id: helioscanary-service:0.0.1-SNAPSHOT-27b096a:342e49e17188abc5e96cce5febc1849362f0a819
Image: helioscanary-service:0.0.1-SNAPSHOT-27b096a
Command: []
Env:
Health check: type: http, port: http, path: /healthcheck
Grace period (seconds): null
Ports: hm=5700/tcp
       http=8080/tcp
Reg: helioscanary/hm=hm
Token:
Volumes: /etc/spotify:/etc/spotify
         /spotify:/spotify

helios --version
Spotify Helios CLI 0.8.213
```

Maybe there's an incompatiblity with that job?

**Comment by rculbertson** [comment]
This happens when the health check is null, and a NPE gets thrown. PR #421 will fix this.

**Comment by evgeny-goldin** [comment]
:+1:
