### ISSUE TITLE
feature request: wait for RUNNING state of multiple jobs

### ISSUE THREAD

**Issue by rasmusbergpalm** [spotify/helios#437]
Hi guys. Thanks for the recent health checking. It's awesome and just what we needed.

In order to wait for our stack to all be running we've had to implement this however:

```bash
waitfor() {
    echo "Waiting for $1 seconds"
    for attempt in $(seq 1 $1); do
        STATUS=$(${HELIOS} status -j ${STACK_TAG} | sed 1d | awk '{print $4}' | sort | uniq)
        ${HELIOS} status -j ${STACK_TAG}
        clear
        if [ "${STATUS}" == "RUNNING" ]; then break; fi
        sleep 1
    done
    if [ "${STATUS}" != "RUNNING" ]; then
        echo "Timed out waiting for $1 seconds"
        exit 1;
    fi
}
```
It would be very nice if there was some kind of command in helios that would do the same.
Maybe it could be a command line argument to the watch command or smth.
Cheers, Rasmus

**Comment by davidxia** [comment]
@rasmusbergpalm Thanks, great to see it's useful for you. Waiting for all instances of a job to be RUNNING seems like a common use case regardless of health checks. I'm not sure how it should be implemented right now, but we'll keep this in mind.

**Comment by rohansingh** [comment]
Maybe could be an extension to `helios watch`, to stop watching when all statuses are `RUNNING`.

**Comment by davidxia** [comment]
Yea I like this idea.

On Thu, Mar 12, 2015 at 1:26 PM, Rohan Singh <notifications@github.com>
wrote:

> Maybe could be an extension to helios watch, to stop watching when all
> statuses are RUNNING.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/helios/issues/437#issuecomment-78537435>.
>



-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by rohansingh** [comment]
I wonder if this is necessary anymore with deployment groups. Effectively  `helios rolling-update` does the same thing.
