### ISSUE TITLE
Declarative language for specifying stacks using helios

### ISSUE THREAD

**Issue by rasmusbergpalm** [spotify/helios#450]
Hi guys. 
What do you think of having a declarative language that would describe a complete stack, and use helios to ensure the state of the declarations?
Basically it would be docker compose (https://docs.docker.com/compose/), with a notion of hosts, powered by helios.

**Comment by rohansingh** [comment]
This type of thing should be possible once we complete #502.

**Comment by davidxia** [comment]
Closing as we're not planning on adding big features like this to helios :(
