### ISSUE TITLE
JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate ARRAY entries

### ISSUE THREAD

**Issue by evgeny-goldin** [spotify/helios#457]
Helios agent `0.8.273` fails to run any command under "root" on Ubuntu 14.04 (VirtualBox) and Docker 1.5:

    vagrant@helios-agent1:~$ helios --version
    Spotify Helios CLI 0.8.273
    vagrant@helios-agent1:~$ sudo su -
    root@helios-agent1:~# id
    uid=0(root) gid=0(root) groups=0(root)
    root@helios-agent1:~# helios --version
    com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate ARRAY entries
     at [Source: [B@4ca8195f; line: 4, column: 8]
    root@helios-agent1:~# helios -z http://192.168.50.50:5181 hosts
    com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate ARRAY entries
     at [Source: [B@4ca8195f; line: 4, column: 8]
    root@helios-agent1:~# uname -a
    Linux helios-agent1 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
    root@helios-agent1:~# lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:  Ubuntu 14.04.1 LTS
    Release:  14.04
    Codename: trusty
    root@helios-agent1:~# docker --version
    Docker version 1.5.0, build a8a31ef
    root@helios-agent1:~#

I'll try downgrading Helios and Docker. Previous Helios versions (two weeks ago) worked just fined with Docker 1.5.

**Comment by evgeny-goldin** [comment]
Downgrading Helios to `0.8.145` didn't help, neither did apt-get purging Docker.

**Comment by evgeny-goldin** [comment]
Java is Oracle 8 JRE:

    root@helios-agent1:~# java -version
    java version "1.8.0_40"
    Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
    Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
    root@helios-agent1:~#

**Comment by evgeny-goldin** [comment]
The error was caused by broken JSON at `"~/.helios/config"` of the "root" user. What could be done, though, is a more explicit error of what went wrong and a path to the JSON file that couldn't be read.

**Comment by davidxia** [comment]
good point, we'll put this in our TODO

On Mon, Mar 23, 2015 at 11:31 AM, Evgeny Goldin <notifications@github.com>
wrote:

> The error was caused by broken JSON at "~/.helios/config" of the "root"
> user. What could be done, though, is a more explicit error of what went
> wrong and a path to the JSON file that couldn't be read.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/helios/issues/457#issuecomment-85050829>.
>



-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by evgeny-goldin** [comment]
Great, thanks!
