### ISSUE TITLE
Authentication against private registry.hub.docker.com repositories

### ISSUE THREAD

**Issue by nexus49** [spotify/helios#462]
Hi there, 
I have been searching for a way to provide auth credentials to pull an image from a private repository. (not necessarily a private registry)

Did i miss that this is somehow possible? I saw that the docker-client is able to provide credentials during pull, but did not see that being used as part of helios. 

Cheers,
Bastian

**Comment by davidxia** [comment]
@nexus49 Our [docker-client](https://github.com/spotify/docker-client) supports private registries (see [docs here](https://github.com/spotify/docker-client/pull/152)), but helios isn't setup to use that functionality yet.

We haven't built this yet bc we haven't needed it and we're quite busy with other things at the moment. But we're open to a PR. The place to change is [here](https://github.com/spotify/helios/blob/master/helios-services/src/main/java/com/spotify/helios/agent/AgentService.java#L208). `dockerClient` needs to be instantiated with the private registry's auth credentials.

**Comment by lvidarte** [comment]
Hi,
I'm trying helios and the agents can't pull images from my private registry.
Is there any advance on this?
Thanks.

    $> helios status
    JOB ID             HOST        GOAL     STATE                     CONTAINER ID    PORTS              
    api:0.6:ab1967d    staging.    START    FAILED (IMAGE_MISSING)                    http=80:9001
