### ISSUE TITLE
Need to start docker service before running helios

### ISSUE THREAD

**Issue by andredasilvapinto** [spotify/helios#463]
It would probably be nice to add the requirement to start docker service before doing helios-up to the docs:
https://github.com/spotify/helios/blob/master/docs/helios_solo.md#linux

Otherwise it will fail and you will get a kind of confusing error message when running the suggested ```docker info``` command:

```
FATA[0000] Get http:///var/run/docker.sock/v1.17/info: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

**Comment by davidxia** [comment]
@andredasilvapinto Thanks for your feedback. I feel like the docs are already clear about this since it states "Ensure you have installed Docker and have configured it correctly so that commands like `docker info` work." If docker isn't running, `docker info` gives you "2015/04/01 15:55:16 Cannot connect to the Docker daemon. Is 'docker -d' running on this host?"

**Comment by andredasilvapinto** [comment]
In my case it didn't give that error but the one I've written in my previous post (maybe this only happens if it is a new docker installation and you haven't started docker before - so the file wasn't created yet). I was not the only one as when I was searching for information regarding the error I've found this http://stackoverflow.com/a/29360837/43046 and eventually fixed it by starting the service.

Regarding the other reference to docker info. I think it is not very obvious (at least it wasn't for me), that docker info would require the service to be on (I thought it could be a command that retrieved only static information about the installation/configuration).

In any case, if you think it is clear this way, I have no objections. I just wanted to refer this as it might have been just something that was forgotten and as I thought it could help other people. Given that it was not the case, I think you should do as you want :) Maybe it was only me that interpreted it wrong. 

You can close the issue if you want.

Regards.

**Comment by davidxia** [comment]
Would `docker ps` instead of `docker info` be a better test command?

**Comment by andredasilvapinto** [comment]
Maybe, but if you want to change it I would suggest simply adding:

"Ensure you have installed Docker, configured it correctly and started the service so that commands like docker info work."

But again, it's not a big problem. Actually I think it is more like a bug in docker which will probably be fixed in the next versions and then the error message from docker info will be much more useful and obvious.
