### ISSUE TITLE
Inconsistent ordering of paths when using container volumes

### ISSUE THREAD

**Issue by mattnworb** [spotify/helios#486]
The usage message for `helios create` specifies that the paths for the `--volume` switch should be in host:container order:

```
$ helios create -h
...
  --volume VOLUME        Container volumes. Specify either a single path to create a data volume,  or  a  source  path and a container path to mount a file or directory from
                         the host. The container path can be suffixed  with  "rw"  or  "ro"  to  create  a read-write or read-only volume, respectively. Format: [host-path]:
                         [container-path]:[rw|ro]. (default: [])
```

This matches [the Docker documentation](https://docs.docker.com/userguide/dockervolumes/) on the order of the parameters.

However internally, [the javadoc](https://github.com/spotify/helios/blob/bb1470077666e19c0ec582b0bc11e016d27b4d5d/helios-client/src/main/java/com/spotify/helios/common/descriptors/Job.java#L91) for Helios' `Job` class in Helios describe these to be in the reversed order, and more importantly when the arguments from the command line or the json file passed to create are interpreted, [the order is reversed](https://github.com/spotify/helios/blob/bb1470077666e19c0ec582b0bc11e016d27b4d5d/helios-services/src/main/java/com/spotify/helios/agent/TaskConfig.java#L309). 

So if you try to create a job using a JSON file like

```
  "volumes" : {
    "/source": "/container"
  }
```

Then the created container actually binds these in reverse order - `/source` inside the container and `/container` on the host.

**Comment by rohansingh** [comment]
Damn. Any thoughts from anyone on whether we fix this by just making the current behavior documented and canonical, or by breaking the old behavior but making it match up with Docker and the docs?

**Comment by mattnworb** [comment]
I would vote for making the current behavior the documented way. While it's a bit ugly since it conflicts with the order from docker, it wouldn't break anything. 

I think the only other options is to do a breaking change as you mention or deprecate this parameter and use a new one with the intended behavior.

**Comment by davidxia** [comment]
Nice catch @mattnworb. I think we should fix docs for now and not break anything.
