### ISSUE TITLE
adding https encryption to the client

### ISSUE THREAD

**Issue by damoon** [spotify/helios#491]
The help function tells me, that the Master endpoints must be of the form "http[s]://heliosmaster.domain.net:<port>".
Using Helios Master behind a https encrypted nginx throws an exception. i looks to me like the helios client is ignoring the https and always using http.

**Comment by rohansingh** [comment]
What exception are you seeing? If nginx is handling SSL termination then the Helios master shouldn't know or care.

**Comment by damoon** [comment]
if the -z param is used wrong the help states:
com.spotify.helios.common.HeliosException: Master endpoints must be of the form "http[s]://heliosmaster.domain.net:<port>"

i added helios behind a nginx with ssl.
"curl https://helios.domain.de/hosts" works and lists the mashines added to helios.

if i run "helios -z https://helios.domain.de:443 hosts" i get the answer:
com.spotify.helios.common.HeliosException: request failed: Response{method='GET', uri=http://helios/hosts/?user=root, status=400, payload=<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
}

So i assume it is the client who does not support https (ignores it and always uses http).

**Comment by damoon** [comment]
i just recreated this with 0.8.444

**Comment by davidxia** [comment]
@damoon You're right. Thanks for the catch. I started stubbing this out here https://github.com/spotify/helios/pull/596
