### ISSUE TITLE
Deployment-group (status) error messages kind of suck

### ISSUE THREAD

**Issue by gimaker** [spotify/helios#553]
1. They don't include the host on which the operation failed. It would be nice to have.
2. They all looks like this:

```
helios -d shared.cloud.spotify.net deployment-group-status megatest                                                                                                            Fri Jul 17 14:30:21 2015

Name: megatest
Job Id: megatest-service:0.0.1-SNAPSHOT-c827f64:58ed2bb
Status: FAILED
Host selectors:
  role = megatest
Error: com.spotify.helios.common.HeliosRuntimeException: deployment for this job is very broken in ZK
```

It would be nice if the `com.spotify.helios.common.HeliosRuntimeException` part wasn't there as it doesn't really add any value (to the user, at least).

**Comment by rohansingh** [comment]
Looks like at least the "very broken in ZK" error message has been replaced with something more useful.
