### ISSUE TITLE
ZDD with rolling-update

### ISSUE THREAD

**Issue by momomagic** [spotify/helios#606]
Looks really good with the (labels and deployment group) update  although will be much better if re-order the rollout tasks more to something like this  

 "rolloutTasks": [
      {
        "action": "DEPLOY_NEW_JOB",
        "target": "helios-agent"
      },
      {
        "action": "AWAIT_RUNNING",
        "target": "helios-agent"
      },
      {
        "action": "UNDEPLOY_OLD_JOBS",
        "target": "helios-agent"
      }
    ] 

Which can easily apply the Zero down time concept , and not effect the previous job in case of timeout ,

**Comment by davidxia** [comment]
This can be a rollout option. The user would need to ensure the job doesn't
use static ports.

On Monday, August 3, 2015, Mo alserr <notifications@github.com> wrote:

> Looks really good with the (labels and deployment group) update although
> will be much better if re-order the rollout tasks more to something like
> this
>
> "rolloutTasks": [
> {
> "action": "DEPLOY_NEW_JOB",
> "target": "helios-agent"
> },
> {
> "action": "AWAIT_RUNNING",
> "target": "helios-agent"
> },
> {
> "action": "UNDEPLOY_OLD_JOBS",
> "target": "helios-agent"
> }
> ]
>
> Which can easily apply the Zero down time concept , and not effect the
> previous job in case of timeout ,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/helios/issues/606>.
>


-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by momomagic** [comment]
Totally agree , its a rollout option and ports dynamically matched with a service registry plugin .

**Comment by gimaker** [comment]
There's an open PR that addresses this: #607

@momomagic: Note that deployment groups are still somewhat experimental and that we are currently working to fix some performance issues.

**Comment by momomagic** [comment]
@gimaker What kind of performance issues do you have there , I have problem with healthchecking is not working with new update

**Comment by gimaker** [comment]
@momomagic Rolling-updates on deployment groups are slow once you start having "many" (10 or so) deployment groups. Nothing breaks, but rolling-updates become slow. We're working to fix that. Other functionality should not be affected.

I don't know of any regressions related to healthchecks -- please submit a separate issue if you're having problems.

**Comment by davidxia** [comment]
closing as #607 has been merged
