### ISSUE TITLE
Creating the id hash when using the rest interface

### ISSUE THREAD

**Issue by cldmnky** [spotify/helios#610]
We are working on a Helios Saltstack module using the Helios rest interface. Most of the requests are straight forward, but the POST to /jobs/ requires a sha1 pregenerated id hash included in the JSON job.

What would be the flow for creating the hash?

**Comment by cldmnky** [comment]
We decided to use the cli interface in the module which worked out well, so this is kind of solved on our side :-)

**Comment by davidxia** [comment]
@cldmnky Glad to hear you found a workaround. FYI clients can now create jobs without specifying a hash. See https://github.com/spotify/helios/pull/678
