### ISSUE TITLE
The right way to Scale up / Down container 

### ISSUE THREAD

**Issue by udomsak** [spotify/helios#616]
I have question about Helios scale/up down container cluster.  What appropriate way to scale up / down cluster container how do you this job ? 
-  By jobs ( 1 container per job ) i see each job create 1 container per time.  It's  correct or not ? 
-  By configuration mangement tool like Puppet, Chef  
-  Do you have community of  Helios by IRC or Slack /  something like that. ?

So if  1 job is container thus if i want to scale up 20container then i need 20jobs right ?  This kind of config i plan to use chef interface with  Helios client.   

Should i do this way. ?  I very glad you are build this powerfull tool and glue with  CI tools.  +1: 

Thank you, 
# me

**Comment by davidxia** [comment]
Hi @udomsak,

Glad to see you using Helios. Currently you can only deploy one jobID (job
name + version + hash) on each Helios agent, ie you can't have the same
jobID running on one agent. At Spotify, we use Puppet to install and run
the Helios agent and our Helios users create 20 agents that each run the
job.

We don't have a public Helios IRC channel or Slack as we're a small team
and probably wouldn't be able to respond to questions. But you are
definitely welcome to start one on freenode or Slack.

On Mon, Aug 10, 2015 at 6:47 AM, udomsak <notifications@github.com> wrote:

> I have question about Helios scale/up down container cluster. What
> appropriate way to scale up / down cluster container how do you this job ?
>
>    - By jobs ( 1 container per job ) i see each job create 1 container
>    per time. It's correct or not ?
>    - By configuration mangement tool like Puppet, Chef
>    - Do you have community of Helios by IRC or Slack / something like
>    that. ?
>
> So if 1 job is container thus if i want to scale up 20container then i
> need 20jobs right ? This kind of config i plan to use chef interface with
> Helios client.
>
> Should i do this way. ? I very glad you are build this powerfull tool and
> glue with CI tools. +1:
>
> Thank you,
> #me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/helios/issues/616>.
>



-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by udomsak** [comment]
Thank you @davidxia :)

**Comment by davidxia** [comment]
@udomsak Each helios agent can register the services it's running into a service discovery tool of your choosing. It's done via a plugin. The current available plugins are [helios-skydns][1] and [helios-consul][2] and you can also make your own :)

  [1]: https://github.com/spotify/helios-skydns
  [2]: https://github.com/SVT/helios-consul

**Comment by udomsak** [comment]
@davidxia Can i pass parameter for limit CPU or Memory usage through Helios or not ?  So if not does helios support for this control or not.?

So what hapen if Container is  use resource over limit  that define as above question it's automatic restart or not. ?

**Comment by davidxia** [comment]
@udomsak Sorry helios doesn't support these settings yet. Helios uses docker-client which does support setting these ([see here][1]), but you'd need to add code to [TaskConfig][2], [SupervisorFactory][3], and probably [AgentService][4].

I don't actually know what happens to containers that hit the resource limits.

  [1]: https://github.com/spotify/docker-client/blob/85170519dc420d69c056da0c45dcd454f125fac2/src/main/java/com/spotify/docker/client/messages/HostConfig.java#L52
  [2]: https://github.com/spotify/helios/blob/master/helios-services/src/main/java/com/spotify/helios/agent/TaskConfig.java
  [3]: https://github.com/spotify/helios/blob/master/helios-services/src/main/java/com/spotify/helios/agent/SupervisorFactory.java#L91
  [4]: https://github.com/spotify/helios/blob/master/helios-services/src/main/java/com/spotify/helios/agent/AgentService.java#L260

**Comment by udomsak** [comment]
@davidxia Actually i plan to use multiple container in under helios-client. One of this application can cause memory leak ( Nodejs ).  To pervent that i need to restart container when they over limit. 

@davidxia Thank you for clarify.  you can close this question but it best to open it and catagolize with Scaling question.

**Comment by carlanton** [comment]
@davidxia Actually, you do support CPU and memory limits since https://github.com/spotify/helios/pull/259 :-P It's not exposed in the helios cli, but you can use them if you are defining your job in JSON!

@udomsak I THINK the container will be restarted by Helios if it's killed by the OOM: https://docs.docker.com/reference/run/#runtime-constraints-on-resources

**Comment by udomsak** [comment]
@carlanton  yep it will restart if over limit but i does not option set in helios client command ( as you refer and @davidxia suggest me for patching.

####  FYI  my scenario example 

###  Per Docker host

- run multiple  nodejs application ( Actionhero ) that have many worker ( assume 15 worker). 
- each application container must does not  consume resource over 70% of system resource.
- each application container must does not have effect with other container when resource over consume.
- run other container for other application ( handle some task ). 

from above requirement i want to limit resource consume.

**Comment by udomsak** [comment]
##  Just Ideas  ( sorry if i miss understand about Helios architecture ). 

for rolling-update ( Zero downtime deployment ).  I trying how to setup policy for helios client when deploy. 

-  deploy new job in background waiting application do some initial when ready switch to new deploy. 
-  current helios do switch from old to new one immediately. 

####  Idea from this scenario must have thrid-party service to handle this. 

- run ha-proxy  with consul-template  for dynamic add  back-end container. 
- remove previous version jobs. ( automatic ).  

idea from this https://github.com/DevTable/gantryd  ( gantryd ) 


####  rolling update host group

- difficult to make it fast without broker or bus messaging help ( parallel deploy ). I not try before for large deployment just THINK.   

- not sure this good or not if we have plugin to connect Helios to connect broker or bus messaging.
