### ISSUE TITLE
Proposal: Deploy & run helios-solo automatically

### ISSUE THREAD

**Issue by rohansingh** [spotify/helios#747]
## Current state

Many projects currently use the [Helios testing framework](https://github.com/spotify/helios/blob/master/docs/testing_framework.md) to bring up Helios jobs in a Helios cluster before running JUnit integration tests. These jobs can be run against a remote cluster, but the usual method is to use [helios-solo](https://github.com/spotify/helios/blob/master/docs/helios_solo.md), which runs a Helios cluster inside a local Docker container.

## Problem

The current setup requires developers to download, install and run helios-solo prior to running Helios-based integration tests. Developers need to keep their local helios-solo installation up-to-date by periodically running `helios-use latest`.  The various `helios-*` scripts packaged with helios-solo are also a source of confusion, since it's not immediately clear that they are separate from the `helios` CLI tool that is a core part of Helios.

## Proposal

When running tests based on the Helios testing framework, if no Helios remote cluster is configured and local local helios-solo instance is found, the testing framework should pull and run the helios-solo image on the local Docker instance. This should be transparent to developers as long as they have Docker running locally.

**Comment by rohansingh** [comment]
@negz

**Comment by negz** [comment]
@rohansingh Should we cap the scope at building `helios-up` functionality into `helios-testing`, or do we need to cover the helios-solo CLI use case(s).

It might be nice to (somehow) build this such that we can spin up solo from either `helios-testing` or via the Helios CLI proper? Otherwise we'll be left with the shell scripts hanging around.

**Comment by rohansingh** [comment]
Yeah, it would be sweet if the whole thing became part of the CLI so that the shell scripts can be killed. But personally I'm also OK with still having the shell scripts. Up to you.

If it looks like replacing all the scripts entirely is going to be a lot of work, it would be nice to have an initial version with limited functionality so that people can benefit from it sooner in their builds.

**Comment by rohansingh** [comment]
Fixed by #769.
