### ISSUE TITLE
How deploy a job using the HTTP api?

### ISSUE THREAD

**Issue by alejandrojnm** [spotify/helios#768]
I trying to deploy a job using the http api, but y get this error :
```
Status Code: 422 
Content-Type: application/json
Date: Thu, 03 Dec 2015 15:34:18 GMT
Helios-Server-Version: 0.8.603
Helios-Version-Status: MISSING
Transfer-Encoding: chunked
```
and the response body show this:
```
{"errors":[]}
```

Any idea???

**Comment by mattnworb** [comment]
What is the request (including all headers) that you are sending?

**Comment by alejandrojnm** [comment]
i send this:
```
http://10.10.10.200:5801/hosts/helios-01/jobs/Tytan:v1:55f1ae3ae433c528939968412610596c19ac5176
```

**Comment by mattnworb** [comment]
@alejandrojnm sorry for the slow response. Does your helios master log anything related to your command?

**Comment by alejandrojnm** [comment]
Now you can do deploy, jobs. I would like you to try the aplicaccion. https://github.com/alejandrojnm/Helios-Manager
