### ISSUE TITLE
Request: Support Etcd as backend as alternative to ZooKeeper

### ISSUE THREAD

**Issue by atombender** [spotify/helios#788]
We're already running everything on Etcd and don't want to maintain yet another consensus thing running on our boxes. Hoping it will be possible to make this pluggable.

**Comment by rohansingh** [comment]
etcd would be nice, but to be honest, I just don't see how this would be possible. Unfortunately a lot of ZooKeeper concepts and primitives are woven throughout the agent and master code.

**Comment by atombender** [comment]
I'd recommend seriously considering it. Becoming consensus-backend-agnostic seems to be a trend (e.g., see Kafka, Mesos, Docker Swarm).

As far as I know, Etcd has feature parity with ZK — hiearchical node tree, autoincrement keys, watches, etc.

The proliferation of consensus databases (there are now three leading ones: Etcd, ZooKeeper, Consul) poses a complexity and system administration problem.

**Comment by davidxia** [comment]
I think this will be a large amount of work and given the direction of the project, we probably won't be able to do implement this ourselves. Any objections if I close this issue?
