### ISSUE TITLE
Documentation of the '--volume' option is wrong

### ISSUE THREAD

**Issue by piccobit** [spotify/helios#789]
The documentation for the <code>--volume</code> option reads:

<code>[container-path]:[rw|ro]:[host-path]</code>

This seems to be wrong and should read IMHO:

<code>[host-path]:[rw|ro]:[container-path]</code>

**Comment by mattnworb** [comment]
See https://github.com/spotify/helios/issues/486. This behavior was accidentally implemented backwards in Helios from how docker itself behaves, but was kept this was to not break compatibility with existing jobs.
