### ISSUE TITLE
Add extra hosts on job creation

### ISSUE THREAD

**Issue by lvidarte** [spotify/helios#796]
Hi, thanks for this amazing tool!

I need to add some hosts to /etc/hosts in the containers.
Is there a way to add hosts on job creation? or it's a bad idea?

The docker option is --add-host

    $ docker run -it --add-host db-static:86.75.30.9 ubuntu

Thanks!

**Comment by mattnworb** [comment]
`extraHosts` support was recently added to docker-client in https://github.com/spotify/docker-client/pull/290 (which is what Helios uses to communicate with docker) so it should be feasible to add this to Helios without having to touch too many other things.

In general though, we think using some sort of [service discovery mechanism](https://github.com/spotify/helios/blob/master/docs/service_registration.md) is usually better for these things (going by your example of telling the container how to find a database), so I'm not sure support for this will be added by us - but we are happy to review any contributions for it.

**Comment by lvidarte** [comment]
Very clear, thanks
