### ISSUE TITLE
remove job CLI command should accept multiple arguments

### ISSUE THREAD

**Issue by mattnworb** [spotify/helios#816]
To allow for removing multiple jobs at once, to avoid unnecessary round trips.

**Comment by davidxia** [comment]
This would be nice, but there are some details to hash out.

`JobRemoveCommand` inherits from `WildcardJobCommand` which searches all jobs for a string containing the job arg passed to `helios remove <job arg>`. `WildcardJobCommand` then errors out if there's zero or more than one matching job.

What should happen if I run `helios remove <job1> <job2> <job3>` and job1 matches one job exactly, job2 matches none, and job3 matches more than one?

**Comment by mattnworb** [comment]
I think in that case the command could just report what happened, for instance

```
removed job 1
no jobs found for job2
cannot remove job3: because ...
```

but yea the need to refactor the command pretty significantly (and also the resource handler on the server side) is what stopped me from implementing this when i proposed it
