### ISSUE TITLE
Class com.spotify.helios.common.Version missing in helios-client on master

### ISSUE THREAD

**Issue by atsticks** [spotify/helios#821]
When checked out the whole stuff and trying to build with our beloved Java toolings, the class

    com.spotify.helios.common.Version

is missing (should be part of the helios-client project). ONly a minor thing, but for the ones not be used to Java this might be an issue.

**Comment by atsticks** [comment]
As a Workaround add something like the following and it will smoothly compile and run AFAIS:

```java
package com.spotify.helios.common;

/**
 * Created by atsticks on 15.01.16.
 */
public class Version {

    public static final String POM_VERSION = "0.8.0-SNAPSHOT";
    public static final String RECOMMENDED_VERSION = "0.8.0-SNAPSHOT";
    private Version(){}   
}
```

**Comment by mattnworb** [comment]
Are you having trouble when building with Maven or with your IDE? 

The file is generated by Maven [here](https://github.com/spotify/helios/blob/master/helios-client/pom.xml#L122-L144)

Some IDEs either don't know how to parse the pom to do things like this, or they don't know to include `target/generated-sources/templated` in the classpath.
