### ISSUE TITLE
Error pulling image

### ISSUE THREAD

**Issue by alejandrojnm** [spotify/helios#823]
Hello, I do not know if this will be a mistake, but when I do the job deploy, if the image is not in that server. helios gives an error down the image, I think it is, because helios is using the registry v1, and I'm using, v2, could that be the problem ??

**Comment by davidxia** [comment]
It's a bit hard to say without more details (eg helios and docker version, error logs, etc), but in a nutshell the helios agent talks to the local docker daemon. Docker handles all the image pulling itself. In recent docker versions, docker will try to pull from the v2 registry and then fall back to v1.

So it doesn't make sense to say "helios is using the registry v1" as helios doesn't know or care. Does this make sense?

**Comment by alejandrojnm** [comment]
@davidxia  you're absolutely right, the problem is, the authentication in the registry, allowed him to access my private network and ready all worked. Thank you so much for everything.
