### ISSUE TITLE
Use a fixed version of skydns

### ISSUE THREAD

**Issue by davidxia** [spotify/helios#901]
Building the helios solo base image will build skydns from [master here](https://github.com/skynetservices/skydns). This repo and its deps change pretty often. So it's hard to figure out what "version" of skydns we've built and put into helios solo base after the fact.

Let's use a fixed version of skydns.

**Comment by davidxia** [comment]
We end up needing commits like https://github.com/spotify/helios/pull/900/commits/1c8b1241ff0d99aa529c63a942e0221ce4f47c73

**Comment by mattnworb** [comment]
I think all you would need to do for this is insert a `git checkout <some tag>` in between [these two lines](https://github.com/spotify/helios/blob/28a4d4ee5b19dbb1e1a687d158ae4dcdab5e1b80/solo/base/Dockerfile#L30-L31)
